// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day6.Models;

[Index("deptid", Name = "IX_Employees_deptid")]
public partial class Employee
{
    [Key]
    public int id { get; set; }

    [Required]
    public string name { get; set; }

    public int age { get; set; }

    public DateOnly hiredate { get; set; }

    [Column(TypeName = "money")]
    public decimal salary { get; set; }

    public int deptid { get; set; }

    [ForeignKey("deptid")]
    [InverseProperty("Employees")]
    public virtual Department dept { get; set; }
}