// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day6.Models;

[PrimaryKey("projid", "deptid")]
[Index("deptid", Name = "IX_Projectdepts_deptid")]
public partial class Projectdept
{
    [Key]
    public int deptid { get; set; }

    [Key]
    public int projid { get; set; }

    public int workinghours { get; set; }

    [ForeignKey("deptid")]
    [InverseProperty("Projectdepts")]
    public virtual Department dept { get; set; }

    [ForeignKey("projid")]
    [InverseProperty("Projectdepts")]
    public virtual Project proj { get; set; }
}