// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lab2.Models;

public partial class Department
{
    public int DeptId { get; set; }

    public string DeptName { get; set; }

    public int MgrSSN { get; set; }

    public DateOnly? MgrHiredate { get; set; }

    public virtual ICollection<Dept_Location> Dept_Locations { get; set; } = new List<Dept_Location>();

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    public virtual Employee MgrSSNNavigation { get; set; }

    public virtual ICollection<Project> Projects { get; set; } = new List<Project>();
}