// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lab2.Models;

public partial class Dependent
{
    public int ESSN { get; set; }

    public string name { get; set; }

    public string Sex { get; set; }

    public DateOnly? Birthdate { get; set; }

    public string Relationship { get; set; }

    public virtual Employee ESSNNavigation { get; set; }
}