// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lab2.Models;

public partial class Dept_Location
{
    public int DeptId { get; set; }

    public string Location { get; set; }

    public virtual Department Dept { get; set; }
}