// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lab2.Models;

public partial class Employee
{
    public int SSN { get; set; }

    public string FName { get; set; }

    public string LName { get; set; }

    public DateOnly? Birthdate { get; set; }

    public string Sex { get; set; }

    public decimal Salary { get; set; }

    public int? SuperSSN { get; set; }

    public int? DeptId { get; set; }

    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    public virtual ICollection<Dependent> Dependents { get; set; } = new List<Dependent>();

    public virtual Department Dept { get; set; }

    public virtual ICollection<Employee_Project> Employee_Projects { get; set; } = new List<Employee_Project>();

    public virtual ICollection<Employee> InverseSuperSSNNavigation { get; set; } = new List<Employee>();

    public virtual Employee SuperSSNNavigation { get; set; }
}