using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LearnItCSD03
{
    public class Complex
    {
        #region Data Fields
        int real;
        int img;
        #endregion
        #region Setters& getters  [Gates]
        public void SetReal(/*Complex this,*/int _real) 
        {
            real =_real;
        }
        public void SetImg(/*Complex this,*/int _img) { this.img = _img; }
        public int GetReal(/*Complex this,*/) { return real; }
        public int GetImg(/*Complex this,*/) { return img; }
        #endregion
        #region Print
        public string Print(/*Complex this,*/)
        {
            //if()
            return $"{this.real}+{img}i";
        }
        #endregion
        #region Function to Add 2 Complex Numbers

        //caller c1
        public Complex Add(/*Complex this,*/Complex right)
        {
            Complex result = new Complex();
            result.real = this.real + right.real;
            result.img = img + right.img;
            return result;
        }
        #endregion

        #region Initialize object
        public void Initialize()
        {
            this.real = 3;
            img = 4;
        }
        public void Initialize(int _real, int _img)
        {
            real = _real;
            img = _img;
        }
        public void Initialize(int _num)
        {
            real = img = _num;
        }
        #endregion

        #region Ctors
        //default ctor generated by o.s [CLR] if there is no such ctor
        public Complex()
        {
            real = 3; img = 4;
        }
        public Complex(int _real, int _img)
        {
            real = _real;
            img = _img;
        }
        public Complex(int _num)
        {
            real = img = _num;
        }
        #endregion
    }
}
