// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day6.Models;

public partial class Department
{
    [Key]
    public int id { get; set; }

    [Required]
    public string name { get; set; }

    [Required]
    public string desc { get; set; }

    [InverseProperty("dept")]
    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    [InverseProperty("dept")]
    public virtual ICollection<Projectdept> Projectdepts { get; set; } = new List<Projectdept>();
}