// <auto-generated />
using System;
using CodeFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirst.Migrations
{
    [DbContext(typeof(CompanyContext))]
    [Migration("20241130223435_v2")]
    partial class v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeFirst.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bref")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Author");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bref = "Health Specialist",
                            JoinDate = new DateTime(2024, 12, 1, 0, 34, 34, 698, DateTimeKind.Local).AddTicks(635),
                            Name = "Ahmed Khattab",
                            Password = "pass123",
                            Username = "ahmed_khatab"
                        },
                        new
                        {
                            Id = 2,
                            Bref = "Technology Enthusiast",
                            JoinDate = new DateTime(2024, 12, 1, 0, 34, 34, 698, DateTimeKind.Local).AddTicks(1695),
                            Name = "Omar Khatab",
                            Password = "pass123",
                            Username = "omar_khatab"
                        },
                        new
                        {
                            Id = 3,
                            Bref = "Business Consultant",
                            JoinDate = new DateTime(2024, 12, 1, 0, 34, 34, 698, DateTimeKind.Local).AddTicks(1709),
                            Name = "Sara Ali",
                            Password = "pass123",
                            Username = "sara_ali"
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Catalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Catalog");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desc = "Latest in technology and innovations",
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 2,
                            Desc = "Health and wellness tips",
                            Name = "Health"
                        },
                        new
                        {
                            Id = 3,
                            Desc = "Latest trends in business and economy",
                            Name = "Business"
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthId")
                        .HasColumnType("int");

                    b.Property<string>("Bref")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CataId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthId");

                    b.HasIndex("CataId");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthId = 2,
                            Bref = "How AI is reshaping industries",
                            CataId = 1,
                            DateTime = new DateTime(2024, 12, 1, 0, 34, 34, 694, DateTimeKind.Local).AddTicks(9450),
                            Desc = "A deep dive into the advancements of Artificial Intelligence and its impact on the world.",
                            Title = "AI Revolution"
                        },
                        new
                        {
                            Id = 2,
                            AuthId = 1,
                            Bref = "Your guide to a healthier lifestyle",
                            CataId = 2,
                            DateTime = new DateTime(2024, 12, 1, 0, 34, 34, 697, DateTimeKind.Local).AddTicks(2101),
                            Desc = "Discover essential tips and tricks to improve your health and well-being.",
                            Title = "Healthy Living Tips"
                        },
                        new
                        {
                            Id = 3,
                            AuthId = 3,
                            Bref = "Key factors driving global economic growth",
                            CataId = 3,
                            DateTime = new DateTime(2024, 12, 1, 0, 34, 34, 697, DateTimeKind.Local).AddTicks(2132),
                            Desc = "An analysis of the factors shaping the global economy in the coming year.",
                            Title = "Economic Growth in 2024"
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.News", b =>
                {
                    b.HasOne("CodeFirst.Models.Author", "Author")
                        .WithMany("News")
                        .HasForeignKey("AuthId");

                    b.HasOne("CodeFirst.Models.Catalog", "Catalog")
                        .WithMany("News")
                        .HasForeignKey("CataId");

                    b.Navigation("Author");

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("CodeFirst.Models.Author", b =>
                {
                    b.Navigation("News");
                });

            modelBuilder.Entity("CodeFirst.Models.Catalog", b =>
                {
                    b.Navigation("News");
                });
#pragma warning restore 612, 618
        }
    }
}
