// <auto-generated />
using System;
using EFDay2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFDay2.Migrations
{
    [DbContext(typeof(CompanyContext))]
    [Migration("20241127181318_v15")]
    partial class v15
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFDay2.Models.Department", b =>
                {
                    b.Property<int>("deptid")
                        .HasColumnType("int");

                    b.Property<string>("deptname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("deptid");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            deptid = 1,
                            deptname = "dotnet",
                            desc = "dotnet"
                        },
                        new
                        {
                            deptid = 2,
                            deptname = "php",
                            desc = "php"
                        },
                        new
                        {
                            deptid = 3,
                            deptname = "flutter",
                            desc = "flutter"
                        });
                });

            modelBuilder.Entity("EFDay2.Models.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("dept_id")
                        .HasColumnType("int");

                    b.Property<string>("fullname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("hiredate")
                        .HasColumnType("date");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("salary")
                        .HasColumnType("money")
                        .HasColumnName("netsalary");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("dept_id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            id = 3,
                            dept_id = 2,
                            fullname = "ali ahmed",
                            hiredate = new DateTime(2005, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            password = "123",
                            salary = 12000m,
                            username = "ali"
                        },
                        new
                        {
                            id = 1,
                            dept_id = 1,
                            fullname = "mostafa mohamed",
                            hiredate = new DateTime(2005, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            password = "123",
                            salary = 12000m,
                            username = "mostafa"
                        },
                        new
                        {
                            id = 2,
                            dept_id = 1,
                            fullname = "ola ahmed",
                            hiredate = new DateTime(2005, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            password = "123",
                            salary = 12000m,
                            username = "ola"
                        });
                });

            modelBuilder.Entity("EFDay2.Models.Project", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("EFDay2.Models.Workfor", b =>
                {
                    b.Property<int>("emp_id")
                        .HasColumnType("int");

                    b.Property<int>("proj_id")
                        .HasColumnType("int");

                    b.Property<int>("workingdays")
                        .HasColumnType("int");

                    b.HasKey("emp_id", "proj_id");

                    b.HasIndex("proj_id");

                    b.ToTable("Worksfor");
                });

            modelBuilder.Entity("EFDay2.Models.Employee", b =>
                {
                    b.HasOne("EFDay2.Models.Department", "department")
                        .WithMany("employees")
                        .HasForeignKey("dept_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");
                });

            modelBuilder.Entity("EFDay2.Models.Workfor", b =>
                {
                    b.HasOne("EFDay2.Models.Employee", "employee")
                        .WithMany("Projects")
                        .HasForeignKey("emp_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFDay2.Models.Project", "project")
                        .WithMany("Employees")
                        .HasForeignKey("proj_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");

                    b.Navigation("project");
                });

            modelBuilder.Entity("EFDay2.Models.Department", b =>
                {
                    b.Navigation("employees");
                });

            modelBuilder.Entity("EFDay2.Models.Employee", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("EFDay2.Models.Project", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
