// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lab2.Models;

public partial class Employee_Project
{
    public int ESSN { get; set; }

    public int PNO { get; set; }

    public int Hours { get; set; }

    public virtual Employee ESSNNavigation { get; set; }

    public virtual Project PNONavigation { get; set; }
}