// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lab2.Models;

public partial class Project
{
    public int PId { get; set; }

    public string PName { get; set; }

    public string PLocation { get; set; }

    public int DeptId { get; set; }

    public virtual Department Dept { get; set; }

    public virtual ICollection<Employee_Project> Employee_Projects { get; set; } = new List<Employee_Project>();
}