// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFDay1.Models;

public partial class Department
{
    public int ID { get; set; }

    public string name { get; set; }

    public string Loc { get; set; }

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}