// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFDay1.Models;

public partial class Student
{
    public int ID { get; set; }

    public string name { get; set; }

    public int? age { get; set; }

    public string adddress { get; set; }

    public int? deptid { get; set; }

    public virtual Department dept { get; set; }
}